name: Publish package ngx-text-editor to Github Package Registry

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@matheuscruzsouza"
      - name: Install npm Packages
        run: npm ci --registry=https://registry.npmjs.org/
      - name: Build
        run: npm run build ngx-text-editor
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: dist
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: deploy_dist
      - name: Publish to GitHub Packages
        run: npm publish projects/ngx-text-editor --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN }}
          FOLDER: deploy_dist/ngx-text-editor
