name: Publish package ngx-text-editor to Github Package Registry

on:
  push:
    paths:
      - "projects/ngx-text-editor/**"
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@matheuscruzsouza"
      - name: Publish to GitHub Packages
        run: |
          npm publish projects/ngx-text-editor --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN }}
