name: Publish package ngx-gundb to Github Package Registry

on:
  push:
    branches: ["main"]
    paths:
    - projects/ngx-gundb/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@matheuscruzsouza"
      - name: Install npm Packages
        run: npm ci --registry=https://registry.npmjs.org/
      - name: Build
        run: npm run build ngx-gundb
      - name: Publish to GitHub Packages
        if: success()
        run: npm publish projects/ngx-gundb --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN }}
