name: Publish package ngx-text-editor to Github Package Registry

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@matheuscruzsouza"
      - name: Install npm Packages
        run: npm ci --registry=https://registry.npmjs.org/
      - name: Publish to GitHub Packages
        run: ng build ngx-text-editor && cd dist/ngx-text-editor && npm publish projects/ngx-text-editor --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN }}
